apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-02-08-deployment
spec:
  selector:
    matchLabels:
      deployment-name: mongodb-02-08-deployment
  replicas: 2
  template:
    metadata:
      labels:
        deployment-name: mongodb-02-08-deployment 
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          env: 
            - name: MONGO_INITDB_DATABASE
              value: database
          ports:
            - containerPort: 27017 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: mongo-cluster-service-02-08
  name: mongo-02-08-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: ionic-cluster-service-port
    port: 27017
    protocol: TCP
  selector:
    deployment-name: mongodb-02-08-deployment
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: mongo-cluster-service-02-08 
  name: mongo-02-08-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: load-balancer-service-port
    port: 27017
    protocol: TCP
  selector:
    deployment-name: mongodb-02-08-deployment