apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-02-08-deployment
spec:
  selector:
    matchLabels:
      deployment-name: api-02-08-deployment
  replicas: 2
  template:
    metadata:
      labels:
        deployment-name: api-02-08-deployment 
    spec:
      containers:
        - name: api-container-02-08
          image: iuri89/api-image-02-08
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: 02-08-api-service-label-cluster-service
  name: api-02-08-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: ionic-cluster-service-port
    port: 3000
    protocol: TCP
  selector:
    deployment-name: ionic-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: 02-08-service-label-cluster-service 
  name: api02-08-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: load-balancer-service-port
    port: 3000
    protocol: TCP
  selector:
    deployment-name: frontend-02-08-deployment