apiVersion: apps/v1
kind: Deployment
metadata:
  name: 21-07-api
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment-name: 21-07-api
  template:
    metadata:
      labels:
        deployment-name: 21-07-api
    spec:
      containers:
        - name: 21-07-api-container
          image: iurib8it148.azurecr.io/apirepository:2df98ab88e4d5f4a2e827616b8a91714f9627049
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: ionic-cluster-service
  name: ionic-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: ionic-cluster-service-port
    port: 3000
    protocol: TCP
  selector:
    deployment-name: api-clusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: ionic-cluster-service-loadbalancer 
  name: ionic-cluster-service-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: load-balancer-service-port
    port: 3000
    protocol: TCP
  selector:
    deployment-name: api-loadBalancer